{
 "title": "Building guardian",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Rooms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Windows open?",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket:\"environment_monitoring\")\r\n  |> range(start:-24h)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"room\" and\r\n    (r._field == \"windowsOpen\")\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Light on?",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket:\"environment_monitoring\")\r\n  |> range(start:-24h)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"room\" and\r\n    (r._field == \"lightOn\")\r\n  )\r\n"
    }
   ]
  },
  { "title": "Building", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Water Consuption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket:\"environment_monitoring\")\r\n  |> range(start:-24h)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"building\" and\r\n    r.host == \"api_scraper\" and\r\n    (r._field == \"waterConsumption\")\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Energy consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket:\"environment_monitoring\")\r\n  |> range(start:-24h)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"building\" and\r\n    r.host == \"api_scraper\" and\r\n    (r._field == \"totalPowerConsumption\" or r._field == \"powerConsumptionDataCenter\" or r._field ==\"solarPowerOutput\")\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n"
    }
   ]
  }
 ]
}